### ISSUE TITLE
create new droplet with _names_ of ssh keys 

### ISSUE THREAD

**Issue by kontrafiktion** [digitalocean/api-v2#115] opened 2014-12-25 18:27 UTC
The API has moved to using names instead of ids almost anywhere.
But it seems that for ssh keys that is not true. I had to use ids instead of names to successfully add the ssh keys to a new droplet.
If the name of an ssh keys is given, the droplet is still created but the ssh key is not added to the droplet.

1) please return an error if the ssh key (name) cannot be found, do not create the Droplet if the given ssh key could not be found
2) please allow to use ssh key names instead of ids

**Comment by ghost** [comment] 2014-12-25 19:35
:+1:

**Comment by phillbaker** [comment] 2015-01-05 19:37
@kontrafiktion you can actually pass the SSH key fingerprint in the droplet create. From the docs (in the table under https://developers.digitalocean.com/#create-a-new-droplet):

> ssh_keys  Array   An array containing the IDs or **fingerprints** of the SSH keys that you wish to embed in the Droplet's root account upon creation.

Please re-open this issue if you have any issues.

**Comment by kontrafiktion** [comment] 2015-01-05 20:14
@phillbaker 

please reopen (I don't know how):

I think _names_ would be

  1) much more convenient than using the fingerprint or the ids
  2) much more in line with the rest of the API

**Comment by kontrafiktion** [comment] 2015-01-05 20:20
Additionally this part of the issue is not solved anyhow:

1) please return an error if the ssh key (name) cannot be found, do not create the Droplet if the given ssh key could not be found

**Comment by ghost** [comment] 2015-01-05 20:36
@phillbaker I would much rather use the ssh key name over the fingerprint for creating.

**Comment by macb** [comment] 2015-01-05 20:54
The repo permission may prevent issues from being re-opened. I went ahead and re-opened it.

One issue with using names is they are not guaranteed to be unique either for a user or between users, you and I could both have the ssh key named `work` for example. This could result in unintended behavior even when scoped to a given user's set of SSH keys.

Fingerprints are a shorthand way of representing an SSH key and can be generated from the key itself, that way you wouldn't have to query the API to find which key you want to use, instead you could get it locally from a utility like `ssh-keygen` (ie `ssh-keygen -lf ~/path/to/public_key | cut -d " " -f 2`). We also enforce uniqueness for these to avoid the confusion above as well as to avoid collisions.

Alternatively, if you wish to use `name`, this could be accomplished by querying for your ssh keys, then filtering by name, and using the `fingerprint` on those in the create.

An example using [jq](http://stedolan.github.io/jq) and `curl`

``` bash
curl "https://$TOKEN:@api.digitalocean.com/v2/account/keys" -s \
  | jq '.ssh_keys[] | select(.name == "work") | .fingerprint'

"ab:cd:ef:12:34:56:78:90:12:34:56:78:1a:2b:3c:4d"
```

**Comment by phillbaker** [comment] 2015-01-05 20:55
@kontrafiktion @gregf in regards to

> please return an error if the ssh key (name) cannot be found, do not create the Droplet if the given ssh key could not be found

it looks like the current implementation silently drops invalid key ids/fingerprints. We should be raising an error for that, we'll get that fixed.

For the name vs. fingerprint let me give some more context: we don't enforce a unique constraint on names, so there would be some logistical/data issues with using names for keys. More importantly, they are not meant as identifiers for keys, but rather as human readable notes, they're more similar to the comment field in an ssh key than a unique identifier. Where we do use names in the API, it's because they're identifiers: e.g. a domain name, image slug, etc.

**Comment by macb** [comment] 2015-01-05 20:56
Too slow @phillbaker :smile_cat:

**Comment by kontrafiktion** [comment] 2015-01-05 21:45
@macb if I have to make a call to retrieve the keys, I can simply use the id (that's what I currently do), -- but both ways entail an extra call to the API

@phillbaker okay, if the names are not meant to be unique, we are doomed ;-(
   I assumed they are unique, nothing in the GUI made me question that assumption.
   And I assume, there _are_ customers with multiple SSH keys with the same name?

Okay, a proposal:
1. allow names
2. throw an error, if there is more than SSH key with the same name, when used by the API
3. add a check for new SSH keys so that the names _are_ unique
- For users that currently use IDs or fingerprints, nothing changes
- For users that would like to use names, everything would be dandy
- problematic case: users that have multiple SSH keys with the same name, who want to start using names

But I admit, I wouldn't give this issue no priority :-(

**Comment by phillbaker** [comment] 2015-01-28 17:53
> it looks like the current implementation silently drops invalid key ids/fingerprints. We should be raising an error for that, we'll get that fixed.

We've deployed a fix for this, you'll now receive errors for invalid ssh keys: https://developers.digitalocean.com/changelog/api-v2/new-droplet-create-validations/

**Closed as completed by phillbaker** 2015-01-28 17:53 UTC
