### ISSUE TITLE
Did date format changed at DO APIs?

### ISSUE THREAD

**Issue by jeevatkm** [digitalocean/api-v2#94] opened 2014-10-12 20:59 UTC
User has reported [Unparseable date exception](https://github.com/jeevatkm/digitalocean-api-java/issues/18).

I would like to confirm, did date format changed from <code>yyyy-mm-dd'T'HH:mm:ss'Z'</code> to <code>yyyy-mm-dd'T'HH:mm:ss.SSS'Z'</code>?

Which is final one?

**Comment by phillbaker** [comment] 2014-10-12 21:01
HI @jeevatkm thanks for checking. This might have been unintentional. I'll check and update this issue with more information.

**Comment by jeevatkm** [comment] 2014-10-12 21:07
Thanks @phillbaker will wait for your response!

**Comment by phillbaker** [comment] 2014-10-12 21:39
Just to be clear - are you seeing this on v1 and v2 or just v2?

**Comment by jeevatkm** [comment] 2014-10-12 21:54
I have just verified v1 and v2, both affected with date format change

**Comment by phillbaker** [comment] 2014-10-12 22:38
@jeevatkm we've found the cause of the problem and will be releasing a patch. I'll close this issue when the patch is pushed.

**Comment by jeevatkm** [comment] 2014-10-12 22:41
Thanks @phillbaker for your quick turn around, I will inform the user about the patch!

**Comment by phillbaker** [comment] 2014-10-13 14:12
@jeevatkm the patch has been deployed.

**Closed as completed by phillbaker** 2014-10-13 14:12 UTC

**Comment by jeevatkm** [comment] 2014-10-13 14:34
Thanks @phillbaker :) I have verified v1 & v2, looks good.
