### ISSUE TITLE
Basic billing info

### ISSUE THREAD

**Issue by kddlb** [digitalocean/api-v2#124] opened 2015-02-23 12:04 UTC
I'd like to be able to see how much credit do I have and how much have I used.

**Comment by phillbaker** [comment] 2015-02-24 17:20
Marking this as a dupe of https://github.com/digitalocean/api-v2/issues/38 and https://github.com/digitalocean/api-v2/issues/58. We're exploring ways of exposing billing information within additional scopes.

**Closed as completed by phillbaker** 2015-02-24 17:20 UTC
Labels: duplicate, enhancement
